### PR TITLE
Implement execLoadAsync

### PR DESCRIPTION
**Pull request by gpfrancis**
- Modify execLoad to use execute_async and rename to execLoadAsync

- Create an execLoad that calls it and waits for results for backwards compatibility. This isn't perfect since we're still doing async calls in parallel if we send multiple rows in data, but it minimises code duplication. We could create a true synchronous version easily enough, it will just be messier.

- Optimise the string processing a bit

### CODE REVIEW

**Comment by genghisken** [comment]
Thanks for this.  Happy to merge the code.

Will be interesting to do some more speed tests with other types of data. One question I have is that since the executeLoadAsync code doesn't wait, we presumably don't know that it's finished, so I'm not sure my end to end test when it runs first time will produce the correct answer if I switch it to use executeLoadAsync (Cassandra may not have finished loading). (Obviously it should complete normally if we just stick to using executeLoad.)

**Comment by gpfrancis** [comment]
That's kind of the point. If you use executeLoadAsync you probably want to explicitly wait for it to complete *somewhere*, just not right away. That's why it needs to return the list of future objects to wait on.

**Comment by genghisken** [comment]
Code is merged. Will create a new release of the code to PyPI.

**Comment by genghisken** [comment]
Code has been pushed to PyPI as gkdbutils version 0.1.0.

**Comment by genghisken** [comment]
Yeah - the slight issue I have is - what if Cassandra never completes the load? Are we giving ourselves a false idea of its load speed (especially of images) if we don't check that the futures objects have completed?  I guess we should store the futures objects somewhere and periodically check them to make sure they completed. We should maybe check then before loading the next batch of alerts...

**Comment by gpfrancis** [comment]
It didn't occur to me to do any speed tests where I *never* waited for the operation to complete because, as you say, that would not be safe and you should not do that in real code. Assuming that it did in fact work without dropping anything I doubt whether it would be a lot faster - checking the result is a purely local operation and should be fast.

**Pull request merged**
